apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "*/20 * * * *" # Cron expression for running at midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: backup # Replace with your Docker image name and tag
            imagePullPolicy: IfNotPresent  # Adjust according to your image pull policy
            # Add any environment variables or volume mounts required by your container
            command:
            volumeMounts:
            - name: backup-volume
              mountPath: /backup-dir  # Mount path in the container
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc  # Name of the PersistentVolumeClaim to mount
          restartPolicy: OnFailure  # Restart the container if it fails
