apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: hiteshyadavm/backup:v1 
            volumeMounts:
            - name: backup-volume
              mountPath: /backup-dir 
            - name: secret-volume
              mountPath: /creds
              readOnly: true
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc  
          - name: secret-volume
            secret:
              secretName: creds
          restartPolicy: OnFailure  


# kubectl create secret generic creds --from-file=creds/token.pickle --from-file=creds/credentials_cc.json
